### ISSUE TITLE
Update Plugins [30/05/2021]

### ISSUE THREAD

**Issue by LooterToGo** [PixelmonToGo/k8s-gitops#11]
Update **Atlantis.**
https://cdn.discordapp.com/attachments/469959623156170754/848344375759208458/Atlantis-3.3.3.jar
Reason: 
- Fixes issues with renaming/saving data files causing duplicate files and subsequent data loss.

Update **AquaGyms**
https://cdn.discordapp.com/attachments/627859895303012365/848345553775230996/AquaGyms-1.12.2-2.3.3-universal.jar
Reason:
- Fixed not being able to delete errored leaders.
- Fixed leader join message being entirely wrong.
- Fixed file names for gyms potentially not being unique.

**Comment by ChipWolf** [comment]
Done
